name: Publish RoeiBajayo.Infrastructure NuGet Package

on:
  push:
    tags:
      - 'v*' # only run on version tags like v1.0.0
  workflow_dispatch: # allows manual triggering

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Restore dependencies
        run: dotnet restore src/RoeiBajayo.Infrastructure.csproj

      - name: Build
        run: dotnet build src/RoeiBajayo.Infrastructure.csproj --no-restore --configuration Release

      - name: Run tests
        run: dotnet test unitests/UnitTestProject.csproj --no-restore --configuration Release

      - name: Pack NuGet package
        run: dotnet pack src/RoeiBajayo.Infrastructure.csproj --no-build --configuration Release --output ./nupkg

      - name: Publish to NuGet
        run: dotnet nuget push "./nupkg/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
